/*
Rename this file to env.js before using
*/
// This is a very ugly workaround
module.exports = { 
    TWITTER_CONSUMER_KEY: 'YOUR TWITTER CONSUMER KEY',
    TWITTER_CONSUMER_SECRET: 'YOUR TWITTER CONSUMER SECRET',
    TWITTER_ACCESS_TOKEN_KEY: 'YOUR TWITTER ACCESS TOKEN KEY',
    TWITTER_ACCESS_TOKEN_SECRET: 'YOUR TWITTER ACCESS TOKEN SECRET'
}